### ДЗ2 - Базовый поток

In [4]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [5]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

In [6]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    s=0     #сумма
    t=[]    #временная матрица
    m3=[]
    r1=len(a) #количество строк в первой матрице
    c1=len(a[0]) #Количество столбцов в 1   
    r2=c1           #и строк во 2ой матрице
    c2=len(b[0])  # количество столбцов во 2ой матрице
    for z in range(0,r1):
        for j in range(0,c2):
            for i in range(0,c1):
                s=s+a[z][i]*b[i][j]
            t.append(s)
            s=0
        m3.append(t)
        t=[]           
    return m3

In [7]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    return np.dot(a,b)

In [8]:
%time
# засечем время работы функции без NumPy
M1 = mult(a, b)
%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)
# проверим корректность
np.abs(np.array(M1) - M2).sum()

Wall time: 0 ns
Wall time: 0 ns


1.7568169141668477e-11

### Задание 2
Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.1665315  0.49801661 0.42612656] [0.71538303 0.47093843 0.31543862]


In [10]:
def scalar_product(a,b):
    res =0
    # traditional code
    for i in range(len(a)): 
        res += a[i] * b[i]
    return res
            

In [11]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [12]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 54.2 ms


0.0

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [13]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    #YOUR CODE
    res = 0
    indexes = np.diagonal(a)
    for i in indexes:
        if(i%2==0):
            res+=i
    return res

In [14]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[2, 2, 3, 3, 4],
       [5, 6, 5, 8, 5],
       [5, 2, 1, 2, 4],
       [1, 8, 2, 9, 4],
       [1, 6, 1, 4, 5]])

In [15]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 15.3 ms


8

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


In [76]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    #result= np.zeros((A.shape[0], A.shape[1]))
    #np.cumsum(A,-1,str,result)
    return np.cumsum(A, axis = 1)  

In [77]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 
#print(A)
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
#%time S2 = np_sec_av(A)
cumsum(a)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [30]:
#функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    Y = np.copy(X)
    Z = np.array([])

    for string in Y:
        for index, item in enumerate(string):
            if index % 2 == 1:
                item = a
            else:
                item **= 3
            Z = np.append(Z, item)
    Z = Z.reshape(Y.shape)
    Z = Z[:, ::-1]
    return np.concatenate((Y, Z), axis=1)
            
        

In [78]:
X = np.array([i for i in range(1, 10, 2)])
print(X.shape)
X
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

(5,)


TypeError: 'numpy.int32' object is not iterable

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [20]:
# функция, решающая задачу с помощью NumPy
from itertools import groupby
def np_encode(a):
    #return zip(*((key, len(tuple(group))) for key, group in groupby(a)))

In [23]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)
np_encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))

Wall time: 0 ns


### Пандас и матплотлиб

In [79]:
import pandas as pd

In [83]:
a = pd.read_csv('https://drive.google.com/uc?id=1il9RDoxwrgUjoOqd9yvdV760_M1AvziI')

### 1. Сколько всего возрастных категорий?

In [96]:
 len(np.unique(a['Age']))

7

### 2. Сколько мужчин из города категории A? (не уникальных ID, а количество строк)

In [97]:
len(a[(a['Gender']=='M')&(a['City_Category']=='A')])

109831

### 3. Сколько женщин от 46 до 50, потративших (столбец Purchase) больше 20000 (условных единиц, в данном случае)? (не уникальных ID, а количество строк)

In [102]:
len(a[(a['Age']>'46')&(a['Age']<'50')&(a['Gender']=='F')&(a['Purchase']>20000)])

270

### 4. Сколько NaN'ов в столбце Product_Category_3?

In [107]:
a['Product_Category_3'].isnull().sum()

373299

### 5. Какую долю (вещественное число от 0 до 1, округлить до 4-го знака) от всех покупателей составляют ВМЕСТЕ мужчины от 26 до 35 лет и женщины старше 36 лет (то есть нужно учесть несколько возрастных категорий)? (вещественное число, округлённое до 4-го знака) (считать не по уникальным ID пользователей, а по суммарному количеству строк)

In [111]:
m_len = len(a[(a['Age']>'26')&(a['Age']<'35')&(a['Gender']=='M')])
f_len = len(a[(a['Age']>'36')&(a['Gender']=='F')])
print('{:.4f}'.format((m_len+f_len)/len(a)))

0.4077


### 6. Какой функцией из matplotlib.pyplot можно нанести отдельные точки на график?

plt.scatter()